### ISSUE TITLE
Source tarball at pypi.org is missing some important files

### ISSUE THREAD

**Issue by mtelka** [stanislavlevin/pyproject_installer#13]
I tried to compare the source tarball at pypi.org and here at github and I found that some important files are missing at pypi.org, namely the `LICENSE` file and `tests`:

<pre>
$ curl -sL https://files.pythonhosted.org/packages/3c/fa/d5cd59b42e7958526e756ee588effd1593d5c4adbc85fa5a55e0f906a876/pyproject_installer-0.3.0.tar.gz -o pypi.tar.gz
$ curl -sL https://github.com/stanislavlevin/pyproject_installer/archive/refs/tags/0.3.0.tar.gz -o github.tar.gz
$ diff <(tar tf github.tar.gz|sort) <(tar tf pypi.tar.gz|sort) 
1,2d0
< pyproject_installer-0.3.0/
< pyproject_installer-0.3.0/backend/
8,9d5
< pyproject_installer-0.3.0/backend/_vendor/
< pyproject_installer-0.3.0/backend/vendored.txt
11d6
< pyproject_installer-0.3.0/backend/_vendor/tomli/
14d8
< pyproject_installer-0.3.0/backend/_vendor/tomli/py.typed
18,22c12
< pyproject_installer-0.3.0/.github/
< pyproject_installer-0.3.0/.github/workflows/
< pyproject_installer-0.3.0/.github/workflows/pipelines.yml
< pyproject_installer-0.3.0/.gitignore
< pyproject_installer-0.3.0/LICENSE
---
> pyproject_installer-0.3.0/PKG-INFO
25,27d14
< pyproject_installer-0.3.0/src/
< pyproject_installer-0.3.0/src/pyproject_installer/
< pyproject_installer-0.3.0/src/pyproject_installer/build_cmd/
29d15
< pyproject_installer-0.3.0/src/pyproject_installer/build_cmd/helper/
33,34d18
< pyproject_installer-0.3.0/src/pyproject_installer/build_cmd/_vendor/
< pyproject_installer-0.3.0/src/pyproject_installer/build_cmd/vendored.txt
36d19
< pyproject_installer-0.3.0/src/pyproject_installer/build_cmd/_vendor/tomli/
39d21
< pyproject_installer-0.3.0/src/pyproject_installer/build_cmd/_vendor/tomli/py.typed
43d24
< pyproject_installer-0.3.0/src/pyproject_installer/install_cmd/
48,72d28
< pyproject_installer-0.3.0/tests/
< pyproject_installer-0.3.0/tests/conftest.py
< pyproject_installer-0.3.0/tests/__init__.py
< pyproject_installer-0.3.0/tests/integration/
< pyproject_installer-0.3.0/tests/integration/conftest.py
< pyproject_installer-0.3.0/tests/integration/__init__.py
< pyproject_installer-0.3.0/tests/integration/test_backends.py
< pyproject_installer-0.3.0/tests/integration/test_buildable.py
< pyproject_installer-0.3.0/tests/integration/test_config_settings.py
< pyproject_installer-0.3.0/tests/unit/
< pyproject_installer-0.3.0/tests/unit/__init__.py
< pyproject_installer-0.3.0/tests/unit/test_build/
< pyproject_installer-0.3.0/tests/unit/test_build/conftest.py
< pyproject_installer-0.3.0/tests/unit/test_build/__init__.py
< pyproject_installer-0.3.0/tests/unit/test_build/test_backend_caller.py
< pyproject_installer-0.3.0/tests/unit/test_build/test_builder.py
< pyproject_installer-0.3.0/tests/unit/test_build/test_pyproject_parser.py
< pyproject_installer-0.3.0/tests/unit/test_install/
< pyproject_installer-0.3.0/tests/unit/test_install/__init__.py
< pyproject_installer-0.3.0/tests/unit/test_install/test_installer.py
< pyproject_installer-0.3.0/tests/unit/test_main.py
< pyproject_installer-0.3.0/tests/unit/test_version.py
< pyproject_installer-0.3.0/tools/
< pyproject_installer-0.3.0/tools/vendored.py
< pyproject_installer-0.3.0/tox.ini
$
</pre>

Could you please add both the `LICENSE` file and tests support to the source tarball at pypi.org?

Thanks.

**Comment by stanislavlevin** [comment]
Thank you for reporting the issue.
Fixed in 0.3.1, uploaded to PyPI.
