### ISSUE TITLE
packaging is already vendored

### ISSUE THREAD

**Issue by mtelka** [stanislavlevin/pyproject_installer#43]
I believe the following text in the `README.md` file needs some update because `packaging` is already vendored:

Installation of build dependencies is up to the caller.
Moreover, parsing of build requirements requires two additional external packages: `packaging` and its dependency `pyparsing`. But since the validation of build dependencies is optional (disabled by default) there is no point to vendor them.

**Comment by stanislavlevin** [comment]
@mtelka, you are right, thanks :)
