### ISSUE TITLE
[Q] Any plans to add support for `pipenv`'s `Pipfile`?

### ISSUE THREAD

**Issue by Ancieg** [stanislavlevin/pyproject_installer#57]
Hi!

Do you have any plans to add support for `pipenv`'s `Pipfile`?

Some projects store metadata only in those files.
Example: https://github.com/nats-io/nats.py

**Comment by stanislavlevin** [comment]
another example:
https://github.com/mapado/haversine

Makes sense, will take a look.

**Comment by stanislavlevin** [comment]
Spec:
https://pipenv.pypa.io/en/latest/pipfile.html
